REFPLTV-279  NDVR-4473 DELIA-33434 DELIA-33546 DELIA-34326 DELIA-34419
NDVR-4473 - [SHAW][VSS] Rewind action exits the Linear Playback

Reason for change: If playTarget after seek is very close to  a discontinuity,
advance playTarget to the discontinuity.
Risks: Low
Test Procedure: Tested on pacexi5 by simulation.
Signed-off-by: Christo Joseph <Christo_Joseph@comcast.com>

Change-Id: Ic43ad3b2d1bd72eebaa7416256001e6e4ab6b042

DELIA-33434 - VSS stream failed due to non synchronized A/V Sequence numbers

Reason for change: If sequence number based synchronization fails, synchronize
using start time.
Risks: Low
Test Procedure: Tested on arris xg1v3 with VSS stream.
Signed-off-by: Christo Joseph <Christo_Joseph@comcast.com>

Change-Id: Ib62becbe900f89c8c458005b49eedcbf343a54d6

DELIA-33546 - [SHAW] [VSS] [XG1V3] Audio loss on PageUP/PageDown action

Reason for change: Audio loss is due to uneven length of audio and video
tracks, since audio track length is less, audio fragment with higher pts
is selected and no audio is heard for some time. Adjust audio and video
playTarget based on discontinuities to fix this.
Risks: Low
Test Procedure: Tested on arris xg1v3 with VSS stream.
Signed-off-by: Christo Joseph <Christo_Joseph@comcast.com>

Change-Id: I5e5d2a60df0a1322d22b7f2281a86cac847385c9

DELIA-33434 - [SHAW] VSS stream failed due to non synchronized A/V Sequence numbers

Reason for change: 1. Fix regression with streams that does not have start-time tag
2. If difference in sequence number between tracks is high, synchronisation fails
for VSS as fragment uri becomes NULL and Init() fails. Switch to start time based
synchronization if the difference is greater than two.
Risks: Low
Test Procedure: Tested on arris xg1v3 with VSS stream.
Signed-off-by: Christo Joseph <Christo_Joseph@comcast.com>

Change-Id: Id2b42b6cb93275a33fa32c9930278b53ae9fe887

DELIA-33434 - [SHAW] VSS stream failed due to non synchronized A/V Sequence numbers

Reason for change: Use #EXT-X-PROGRAM-DATE-TIME to synchronize VSS
streams identified through string "?sz=". Wait for other track's
playlist update if discontinuity is not found in other track's current
index. Ignore discontinuity during initialization as discontinuity is
required only when injection is intended. Check other track's discontinuity
only if fragment is discontinous instead of checking it during tag parse.
Risks: Low
Test Procedure: Tested on arrisxg1v3 with VSS streams.
Signed-off-by: Christo Joseph <Christo_Joseph@comcast.com>

Change-Id: I94fc004704f7e30b052e3c22eb9f9e29b9b2a99e

DELIA-33434 - [SHAW] VSS stream failed due to non synchronized A/V Sequence numbers

Reason for change: After culling starts by FOG, other track's discontinuity
check can lead to deadlocks as playTarget does not have same start position
as that of the discontinuity index. Reduce total culled duration from
playtarget before checking against discontinuity index.
Risks: Low
Test Procedure: Tested on arrisxg1v3 with VSS streams.
Signed-off-by: Christo Joseph <Christo_Joseph@comcast.com>

Change-Id: If72482ec79d3d3ddcdddb5938e63d0d89581d2a1

DELIA-33434 - [SHAW] DRM Metadatas are not cleaned in VSS stream

Reason for change: With DRM rotation happening more metadata are queued up
in DRM Manager increasing the loop and performance . Instead of cleaning
at channel change its removed after playlist update
Risks: Low
Test Procedure: Tested on arrisxg1v3 with VSS streams.

Change-Id: I70fff10e1dada2df401328ca63fb906ae29906f3
Signed-off-by: jkumar <Jai_Kumar@cable.comcast.com>

DELIA-33434 - [SHAW] VSS stream failed due to non synchronized A/V Sequence numbers

Reason for change: Freeze is observed because of back to back discontinuity
tags present in one track when the other track only has one discontinuity
at that area. This leads to first track's injection to be stopped. Use last
processed discontinuity position to ignore such discontinuities.
Audio loss during transition caused by different start timestamps after
discontinuity. Sync tracks by skipping fragments as required if time tag
present after discontinuity.
Risks: Low
Test Procedure: Tested VSS playback on arrisxi6
Signed-off-by: Christo Joseph <Christo_Joseph@comcast.com>

Change-Id: Iba5da6d161b3a83e435e1b56cb2b0fb4af780cd9

DELIA-34326 - [SHAW] DRM Memory release across stream switch/ch change

Reason for change: With DRM rotation happening more metadata are queued up in DRM Manager increasing the loop and performance .
                When Metadata is freed adaptor and listner need to be freed along with aveDrmManager instance.
                Also added mutex protection for sAveDrmManager vector accessed by multiple functions
Risks: Low
Test Procedure: Tested on arrisXi6 with VSS streams and on Xi5 muxed content

Change-Id: Ia53050b24a4f0167c58acaac5408c1eb4ab937ed
Signed-off-by: jkumar <Jai_Kumar@cable.comcast.com>

DELIA-33434 - [SHAW] Intermittent crash on VSS switching

Reason for change: Follow-up commit to reset discontinuity index count
on Flush index which was missed and causes intermittent crashes. Also
defined ave drm manager mutex outside AVE_DRM macro to fix compilation
on pi/ ubuntu.
Risks: Low
Test Procedure: Tested on ArrisXi6 with VSS streams.
Signed-off-by: Christo Joseph <Christo_Joseph@comcast.com>

Change-Id: I112cff4eaa31d9495304d1dfa2a076cac241c6f5

DELIA-34326 - [SHAW] DRM Memory release across stream switch/ch change

Reason for change: If common keys were used across video /audio, need checks before releasing the metadata
                   Add checks to ensure video playlist refresh doesnt release audio related meta and viceversa
                   When common Meta is removed from both playlist,then only release called.
Risks: Low
Test Procedure: Tested on arrisXi6 with VSS streams

Change-Id: Ib6d2bdc266cd90d48fd9e1a27c73df778b157786
Signed-off-by: jkumar <Jai_Kumar@cable.comcast.com>

DELIA-33434 - [SHAW] Freeze due to delay in other tracks discontinuity

Reason for change: In discontinuity validation logic, other track's
discontiniuty is not receivied on the first playlist update some times.
To handle this scenario, increase number of playlist refreshes to wait
for discontinuity.
Risks: Low
Test Procedure: Tested on ArrisXi6 with VSS streams.
Signed-off-by: Christo Joseph <Christo_Joseph@comcast.com>

Change-Id: I77a2644a615d9ad382b4c19fa9da0491beaf543e

DELIA-34419: SIGSEGV in AveDrm::SetState

Reason for change: Reorder signalling DRM error and SetState. Crash happened
because we were setting SetState after notifying error upstream
which will cause mutex to be released
Test Procedure: tested on arris xg1v4
Risks: None
Signed-off-by: Vinish K B <Vinish_KorasseryBalakrishnan@comcast.com>

Change-Id: Ifaa0deba5cded6420d2c4830694a5aa39b1a43a0

DELIA-33434 - [VSS] Temperory audio loss during page up/ page down

Reason for change: During track synchronization based on date time tag
or sequence number, update playTarget to valid start time of a fragment
to allow proper synchronisation. Correct offset calculated during
synchronisation based on discontinuity. Use synchronisation based on
discontinuity for TSB content if not playing at live point when possible.
Risks: Low
Test Procedure: Tested on ArrisXi6 with VSS streams.
Signed-off-by: Christo Joseph <Christo_Joseph@comcast.com>

Change-Id: I6d24feb88016e63196bff70799ee7e23cf261e05
(cherry picked from commit eac01d3d3d4a23c659747d6eb62a8c830f277f02)

DELIA-34326 - [SHAW] DRM Memory release across stream switch/ch change

Reason for change:  Prevent adding usercount for same tracktype if already set for a metadata.This will prevent
                    removing it. Also when meta is added with Key tag, it was getting removed every playlist refresh
                    and added back until key tag is present . If Meta is not used , it will not be removed .
                    Coding style update - Add 'm' to member variables of class .
Risks: Low
Test Procedure: Tested on arrisXi6 with VSS streams

Change-Id: If73b9fd78c3bfeca7005228e596a52d7e368192b
Signed-off-by: jkumar <Jai_Kumar@cable.comcast.com>
(cherry picked from commit 3151462f2c397af6065a66634cbf4e85e5f9f9e8)

REFPLTV-279 Fix build failures caused by aamp

rdk-next latest builds are failing for EMU & RPI video both HYB & MC
'error: 'aveDrmManagerMutex' was not declared in this scope' in drm/ave/drm.cpp

aveDrmManagerMutex is declared inside '#ifdef AVE_DRM', but CMF builds
do NOT have ave. So moving it outside the #ifdef.

Change-Id: Ie086d43495642b7122ddd956b452eccefa36beec