REFPLTV-279 Fix build failures caused by aamp
rdk-next latest builds are failing for EMU & RPI video both HYB & MC
'error: 'aveDrmManagerMutex' was not declared in this scope' in drm/ave/drm.cpp

aveDrmManagerMutex is declared inside '#ifdef AVE_DRM', but CMF builds
do NOT have ave. So moving it outside the #ifdef.

Change-Id: Ie086d43495642b7122ddd956b452eccefa36beec