Revert "DELIA-57127: Improvement for RDK-36554,"
This reverts commit e27ed4beb2fe49eaef96e15f2a200c4fd07148b8.

Reason for revert: This is causing build errors:
| /home/jenkins/jenkinsroot/workspace/build-rpi-hybrid-wpe-nosrc/EXEC_0/build-raspberrypi-rdk-hybrid/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/aamp/1.99-r0/git/priv_aamp.cpp:1325:1: error: 'PrivateInstanceAAMP::mcurrent_keyIdArray' should be initialized in the member initialization list [-Werror=effc++]
|  1325 | PrivateInstanceAAMP::PrivateInstanceAAMP(AampConfig *config) : mReportProgressPosn(0.0), mAbrBitrateData(), mLock(), mMutexAttr(),
|       | ^~~~~~~~~~~~~~~~~~~
| /home/jenkins/jenkinsroot/workspace/build-rpi-hybrid-wpe-nosrc/EXEC_0/build-raspberrypi-rdk-hybrid/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/aamp/1.99-r0/git/priv_aamp.cpp:1325:1: error: 'PrivateInstanceAAMP::mDynamicDrmDefaultconfig' should be initialized in the member initialization list [-Werror=effc++]
| cc1plus: some warnings being treated as errors
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.

Change-Id: I40d98588f16dbde76e73af61c0e24ba2db753001